# Generated by Django 3.1 on 2021-01-01 15:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_auto_20201129_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provin', models.CharField(blank=True, choices=[('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Fargʻona', 'Fargʻona'), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ('Qoraqalpogʻiston', 'Qoraqalpogʻiston'), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Qashqadaryo', 'Qashqadaryo'), ('Toshkent', 'Toshkent')], max_length=200, null=True, verbose_name='Viloyat')),
                ('name', models.CharField(max_length=50, verbose_name='Markaz nomi')),
                ('logo', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Logo')),
                ('list_of_courses', models.CharField(max_length=250, verbose_name='Kurs Nomi')),
                ('address', models.CharField(max_length=100, verbose_name='Manzil')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon Nomer')),
                ('website', models.CharField(max_length=50, verbose_name='Sayt manzili')),
            ],
            options={
                'verbose_name': 'Markaz',
                'verbose_name_plural': 'Markazlar',
            },
        ),
    ]
