# Generated by Django 3.1.5 on 2021-01-24 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secondapp', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provin', models.CharField(blank=True, choices=[('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Fargʻona', 'Fargʻona'), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ('Qoraqalpogʻiston', 'Qoraqalpogʻiston'), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Qashqadaryo', 'Qashqadaryo'), ('Toshkent', 'Toshkent')], max_length=200, null=True, verbose_name='Viloyat')),
                ('school_name', models.CharField(max_length=250)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='O`quv markazi Logo')),
                ('state', models.CharField(blank=True, max_length=250, null=True, verbose_name='Davlat')),
                ('contact_number', models.IntegerField(verbose_name='Telefon Nomer')),
                ('contact_number2', models.CharField(max_length=250, verbose_name='Shifrlangan T.Nomer')),
                ('address', models.CharField(max_length=250)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lang', models.ManyToManyField(to='secondapp.Language')),
                ('science', models.ManyToManyField(to='secondapp.Science')),
            ],
            options={
                'verbose_name': 'O`quv Markaz',
                'verbose_name_plural': 'O`quv Markazlar',
            },
        ),
    ]
