# Generated by Django 3.1.5 on 2021-01-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0005_language_schoolregister_science'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolregister',
            name='lang',
        ),
        migrations.AddField(
            model_name='schoolregister',
            name='lang',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Til'),
        ),
        migrations.RemoveField(
            model_name='schoolregister',
            name='science',
        ),
        migrations.AddField(
            model_name='schoolregister',
            name='science',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Fan'),
        ),
    ]
