# Generated by Django 3.1.5 on 2021-01-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0006_auto_20210124_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolregister',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolregister',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolregister',
            name='telegran',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolregister',
            name='website',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolregister',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
