# Generated by Django 3.1.5 on 2021-01-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0007_auto_20210124_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolregister',
            old_name='telegran',
            new_name='telegram',
        ),
    ]
