# Generated by Django 3.1 on 2021-02-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0008_auto_20210124_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolregister',
            name='contact_number',
            field=models.FloatField(verbose_name='Telefon Nomer'),
        ),
    ]
