# Generated by Django 3.1 on 2021-02-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0009_auto_20210203_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolregister',
            name='home_call',
            field=models.IntegerField(default=1, verbose_name='Domashniy Telefon yoki Faks'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolregister',
            name='contact_number',
            field=models.IntegerField(verbose_name='Telefon Nomer'),
        ),
        migrations.AlterField(
            model_name='schoolregister',
            name='contact_number2',
            field=models.CharField(blank='True', max_length=250, null='True', verbose_name='Shifrlangan T.Nomer'),
        ),
    ]
