# Generated by Django 3.1 on 2021-02-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0010_auto_20210203_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolregister',
            name='contact_number2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Shifrlangan T.Nomer'),
        ),
        migrations.AlterField(
            model_name='schoolregister',
            name='home_call',
            field=models.IntegerField(blank=True, null=True, verbose_name='Domashniy Telefon yoki Faks'),
        ),
    ]
